/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wanggang_www_ndksodemo_JNIUtils */

#ifndef _Included_com_wanggang_www_ndksodemo_JNIUtils
#define _Included_com_wanggang_www_ndksodemo_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wanggang_www_ndksodemo_JNIUtils
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wanggang_www_ndksodemo_JNIUtils_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
